[elk]
elk ansible_host=192.168.56.10 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/elk/virtualbox/private_key ansible_python_interpreter=/usr/bin/python3

[baseline]
baseline ansible_host=192.168.56.20 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/baseline/virtualbox/private_key ansible_python_interpreter=/usr/bin/python3 server_mode=baseline service_name=baseline-nginx

[hybrid]
hybrid ansible_host=192.168.56.30 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/hybrid/virtualbox/private_key ansible_python_interpreter=/usr/bin/python3 server_mode=hybrid service_name=hybrid-oqs-nginx

[client]
client ansible_host=192.168.56.40 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/client/virtualbox/private_key ansible_python_interpreter=/usr/bin/python3

[webservers:children]
baseline
hybrid

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
elk_ip=192.168.56.10
baseline_ip=192.168.56.20
hybrid_ip=192.168.56.30
client_ip=192.168.56.40
elastic_version=8.13.4
