---
- name: Install Elastic GPG key
  shell: |
    set -e
    wget -qO- https://artifacts.elastic.co/GPG-KEY-elasticsearch | gpg --dearmor > /usr/share/keyrings/elastic-keyring.gpg
  args:
    creates: /usr/share/keyrings/elastic-keyring.gpg

- name: Add Elastic apt repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/elastic-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main"
    filename: elastic-8.x
    state: present

- name: Update apt cache after adding Elastic repo
  apt:
    update_cache: true
